SMS 인증, 검증 API 추가
Stageus/kkujjang-backend pull request #19
Opened 2023-12-26 15:43 UTC by Godbell

* `GET /user/auth-code?receiverNumber=[tel]` to send
* `POST /user/auth-code/check` to check (body contains key `authCode`)

2023-12-26 21:50 UTC, GulSauce requested changes

2023-12-26 21:50 UTC, GulSauce commented on router/user.js
> +    '잘못된 전화번호입니다.',
validation.js 내의 코드
```
throw {
      statusCode: 400,
      message: `올바르지 않은 형식입니다: ${targetType}`,
      messages,
    }
```
에서 볼 수 있 듯, throw하면
message: 올바르지 않은 형식입니다: 잘못된 전화번호입니다.
와 같이 어색하게 출력될 것 같습니다.

저는 기존에 활용할 때, 첫 번째 매개변수로 준 변수명을 그대로 적었습니다.
'잘못된 전화번호입니다.' -> 'receiverNumber'로 변경하면
message: 올바르지 않은 형식입니다: receiverNumber로 throw되어
매개변수로 전해준 변수가 잘못된 형식임을 알 수 있습니다.

이에 대해서 검토 부탁드립니다!

2023-12-26 21:50 UTC, GulSauce commented on router/user.js
> +    validation.checkLength(8, 20),
요구사항 명세서에 따르면 고정 13자리로 설정되어있고
figma 스토리보드를 보면 010이 기본 값이기도 합니다
![1](https://github.com/Stageus/kkujjang-backend/assets/139232765/4b313600-7fab-4613-94dd-c23b65440e5a)
(물론, 드롭다운 요소로 설정하여 010 이외의 다른 시작 숫자를 고를 수 있는 여지를 주고 있긴 합니다)
앞선 이유들로, 문자를 받을수있고 하이픈 포함 13자리인 전화번호 양식은 010-xxxx-xxxx밖에 없다고 생각하여
저는 정규표현식을
```
validation.check(
    phone,
    'phone',
    validation.checkExist(),
    validation.checkRegExp(/^010-\d{4}-\d{4}$/),
  )
```
와 같이 표현하였습니다.

프론트 분들에게도 어떤 번호들을 인증 요청해줄지를 다시 물어보고
(특히 드롭다운 목록에 넣을 값들이 무엇인지)
010-xxxx-xxxx만 사용할지 아니면 다른 전화번호 양식이 있는지를 결정하여
그에 맞는 정규표현식으로 작성해야할 것 같습니다.

이에 대해서 검토부탁드립니다!

2023-12-27 04:46 UTC, Godbell commented on router/user.js
> +    '잘못된 전화번호입니다.',
수정하여 반영했습니다!

2023-12-27 04:47 UTC, Godbell commented on router/user.js
> +    validation.checkLength(8, 20),
수정하여 반영했습니다!

2023-12-27 04:47 UTC, Godbell reviewed
리뷰 주신 내용으로 수정하였습니다.

2023-12-27 05:24 UTC, GulSauce approved these changes
LGTM 👍

2023-12-27 05:25 UTC, merged