Feat: inquiry router
Stageus/kkujjang-backend pull request #35
Opened 2024-01-11 07:45 UTC by GulSauce

2024-01-11 10:25 UTC, Godbell commented on router/inquiry.js
> +            inq_thread.updated_at, inq_article.count`,
이건 그냥 질문인데, 혹시 여기서 `GROUP BY`가 쓰이는 이유가 무엇인가요?

2024-01-11 10:38 UTC, Godbell requested changes
바뀐 테이블명도 반영 부탁드립니다.

2024-01-11 10:38 UTC, Godbell commented on middleware/inquiry.js
> +export const validateInquiryupload = async (req, res, next) => {
이 부분은 multer 리팩터링 이후 검토하도록 하겠습니다.

2024-01-11 10:38 UTC, Godbell commented on middleware/inquiry.js
DB 관련 작업은 라우터에서 진행해 주시기 바랍니다. 예외처리 미들웨어에선 말 그대로 입력값의 예외처리만 진행해야 합니다. 특히, 조건식 build하는 부분은 반드시 라우터 내의 쿼리문 내에서 수행해 주시기 바랍니다. 조건식 build 부분은 다른 라우터에서 사용하는 방식 참고 바랍니다.

2024-01-11 10:55 UTC, GulSauce commented on middleware/inquiry.js
예외처리 미들웨어로 규정한 이상 어쩔수 없네요
알겠습니다

2024-01-11 10:55 UTC, GulSauce commented on router/inquiry.js
> +            inq_thread.updated_at, inq_article.count`,
그래야만 GROUP에 해당되지않는
```
 ARRAY_AGG(
          JSON_BUILD_OBJECT(
            'isAnswer', CASE WHEN usr.authority_level = $2 THEN true ELSE false END,
            'authorId', inq_article.author_id,
            'content', inq_article.content,
            'file', inq_files.files
          ) ORDER BY inq_article.created_at ASC
        ) AS list
```
이것이 배열로써 쿼리 결과 JSON의 한 key에 들어 갈 수 있기 때문입니다

2024-01-12 19:12 UTC, GulSauce commented on middleware/page.js
> +    page,
parseInt(page)로 하면 원본 검증이 아닌 pareInt된 문자열만 검증하므로 수정하였습니다
(const {page} = req.parms에서 aaa666같은 값을 그대로 받아오는 문제 가능성)

2024-01-15 09:33 UTC, Godbell requested changes

2024-01-15 09:33 UTC, Godbell commented on middleware/inquiry.js
> +  await multer(req, key, option)
이 부분(Line 154)에서 아직 예외처리 모듈에서 업로드 수행하고 있습니다. `validateInquiryupload()` 함수 내용은 미들웨어가 아닌 라우터 핸들러에서 수행해야 하는 작업으로 보입니다. 만약 multer 코드 내에서 파일 예외처리 따로, 파일 업로드 따로 구현된 경우였다면 둘을 분리해서 작성해주었을 테지만, multer에서 파일 예외처리와 업로드 동시에 진행하기 때문에 예외처리 미들웨어에 들어가기에는 어렵습니다.
이 부분은 핸들러로 이동 바랍니다.

2024-01-15 09:33 UTC, Godbell commented on middleware/inquiry.js
아직 미들웨어 함수 내에서 condition String을 만들어 주고 있습니다. 예외처리 모듈에서는 말 그대로 예외처리, 즉 type과 needsAnswer에 알맞은 값이 들어왔는지만 확인하고 SQL Query 빌드 작업은 핸들러에서 진행해야 합니다.

사실 이름을 `@middleware`로 정한 만큼 예외처리 모듈이 아니어도 작성할 수는 있습니다. 물론 validate라는 이름이 붙은 함수 내에 존재해서는 안 되겠죠. 다만, 그렇다고 하더라도 굳이 미들웨어에서 진행할 이유는 없는 작업입니다. 

왜냐하면, 라우터 핸들러에서 PreparedStatement를 사용하기 위한 쿼리를 만드는 부분이 이미 있으며 SQL 관련 작업은 라우터 핸들러에서 수행하고 있기 때문입니다. 쿼리를 만든다고 표현한 이유는 템플릿 리터럴(백틱)을 사용해 변수를 넣는 부분과 `$`을 사용해서 변수를 넣어 주는, 즉 PreparedStatement를 이용하는 부분이 있기 때문입니다. 즉 조건식을 만드는 부분만 따로 미들웨어에 분리할 이유가 없습니다. 

결론적으로 SQL condition 문자열을 만드는 부분을 핸들러에 배치하는 것을 권장합니다.

2024-01-15 09:33 UTC, Godbell commented on router/inquiry.js
> +      : null
참일 때만 작업을 하기 위해서는 `&&` 연산자를 사용합니다.
동일하게 구현한 다른 부분도 수정 바랍니다.
```js
searchedInquiry.length === 0 && searchedInquiry.push({ lastPage: 0, list: [] })
```

2024-01-15 10:37 UTC, GulSauce commented on middleware/inquiry.js
> +  await multer(req, key, option)
별도의 미들웨어로 분리했습니다

2024-01-15 10:38 UTC, GulSauce commented on router/inquiry.js
> +      : null
변경완료했습니다!

2024-01-15 10:38 UTC, GulSauce commented on middleware/inquiry.js
핸들러로 이동했습니다

2024-01-15 12:09 UTC, Godbell approved these changes
lgtm

2024-01-15 12:09 UTC, merged