Feat: Create exception utility
Stageus/kkujjang-backend pull request #4
Opened 2023-12-18 09:12 UTC by GulSauce

- Create chkExist : null, undefined, 비어있는 스트링 체크
- Create chkLength : 최소 길이, 최대 길이 확인
- Create chkStd : 정규 표현식과의 일치여부 확인
- Create chkSame : 주어진 문자열과 일치여부 확인
- Create check : 검사할 스트링, 적절한 예외처리 함수들을 제공받아 reduce과정 수행

2023-12-18 09:47 UTC, Godbell requested changes
전반적으로 작명 관련해서 한 번 점검해 주세요! 반영 완료된 사항에는 꼭 각각 댓글 달아주시기 바랍니다.

2023-12-18 09:47 UTC, Godbell commented on utility/exception.js
> +export { check, chkExist, chkLength, chkStd, chkSame };
마지막에 export 목록 정리하는 대신 export할 요소의 선언문에 export를 붙여 주세요!
```js
export const func = () => {
  ...
}
```

2023-12-18 09:47 UTC, Godbell commented on utility/exception.js
프로그래밍에서 `exception`은 일반적으로 `throw` 구문으로 발생시키는 오류를 뜻합니다. 예를 들면 배열 인덱스를 초과했을 때 발생하는 `ArrayOutOfBoundException`, 수를 0으로 나누었을 때 발생하는 `DivideByZeroException` 등이 있습니다.
여기서 다루는 예외처리는 입력값 형식 검사인데, `exception.js`라고 하면 Exception 처리 미들웨어로 혼동할 여지가 있습니다. `formatChecker.js`, `format.js`, `validation.js` 등의 이름이 적절해 보입니다.

2023-12-18 09:47 UTC, Godbell commented on utility/exception.js
> +      throw JSON.stringify({
1. `stringify`하지 않고 객체를 직접 `throw`해 주세요. 이후 오류 객체에 접근하기 쉬워집니다.
2. 자체적인 오류 코드를 쓰는 것이 아니라 HTTPS Status Code를 사용하는 거라서 `errorCode`보다는 `status`라는 이름이 더 적절해 보이네요!
```js
throw {
  statusCode: ...,
  message: ...
}
```

2023-12-18 09:47 UTC, Godbell commented on utility/exception.js
> +const check = (...as) => combine((as, f) => f(as), as);
1. 매개변수에 어떤 것이 들어가는지 더 명확하게 나타내기 위해 `as`보다 정확한 이름을 지정해 주세요. `checkers`, `checkFunctions`, `functions` 등이 있겠습니다.
2. 함수가 하는 일을 더 자세히 설명하는 이름이 필요합니다.`checkFormat`, `validateFormat`, `checkValidity` 등이 있겠습니다.

2023-12-18 09:47 UTC, Godbell commented on utility/exception.js
+ `@router/test`에 본 모듈 사용하는 테스트 한 번 작성해서 잘 작동하는지 확인한 뒤 테스트까지 함께 커밋해 주세요.

2023-12-18 09:47 UTC, Godbell commented on utility/exception.js
> +
아래의 함수의 반환값으로 좀 더 많은 정보를 전달해야 합니다.
위의 함수에서 `msg`에 오류 발생 시 특정한 메시지만을 전달하는 게 아니라 어떤 함수를 통과하지 못했는지 그 메시지를 자세히 기술할 수 있어야 합니다. 이런 식으로 사용할 수 있으면 더 좋겠네요! throw될 오류 객체에는 해당 메시지를 배열로 저장하면 더 좋겠습니다.

사용 예시
```js
check(
  [검사할 문자열],
  checkSomething([검사 통과 못하면 알려줄 메시지]),
  checkSomething([검사 통과 못하면 알려줄 메시지]),
  ...
)
```

throw된 오류 객체 예시
```js
{
  statusCode: 400,
  messages: ["검사 통과 못하면 알려줄 메시지1", "검사 통과 못하면 알려줄 메시지2", ...]
}
```

2023-12-18 09:47 UTC, Godbell commented on utility/exception.js
> +    return (...bs) => curry(f)(...as, ...bs);
`as`, `bs` 대신에 `inputFunctions`와 `functionsToAppend`는 어떨까요? 특히 `as`는 전치사 as와 헷갈립니다.

2023-12-19 13:51 UTC, Godbell commented on router/test.js
> +import * as v from '../utility/validation'
실제로 사용할 엔드포인트에서 불러올 때는 더 명확한 이름을 붙여 주세요. 테스트 코드라서 굳이 수정은 하지 않고 merge하겠습니다.

2023-12-19 15:06 UTC, GulSauce commented on utility/validation.js
> +  }
완료

2023-12-19 16:38 UTC, Godbell approved these changes
LGTM :D

2023-12-19 16:39 UTC, merged

2023-12-19 16:40 UTC, Godbell commented
LGTM!